### ISSUE TITLE
how to integrate ibatis-2 with spring 4.x

### ISSUE THREAD

**Issue by mokhtar-ahmed** [mybatis/ibatis-2#19]
it seems that spring 4.x doesn't support ibatis anymore

**Comment by hazendaz** [comment]
That is correct.  If you want to use spring 4 then you will need to upgrade to mybatis 3 and use mybatis spring module.  There won't be any support to make mybatis 2 work with spring 4.  It's too much work with too little gain.  However if you are stuck there and have time go take the ibatis support in spring 3 and create a subproject.  I'd be happy to pull that in for continued legacy support for this type of setup but don't have the time to do it myself.  Although I know others could benefit in the short term as a stop gap.


Sent by Outlook for Android





On Sun, Nov 1, 2015 at 2:39 AM -0800, "mokhtar-ahmed" <notifications@github.com> wrote:
it seems that spring 4.x doesn't support ibatis anymore

---
Reply to this email directly or view it on GitHub:
https://github.com/mybatis/ibatis-2/issues/19

**Comment by emacarron** [comment]
Seems that they removed the ibatis package from the spring-orm bundle.

I suppose that the old Spring 3.x integration code should work with no change, so we can think about publishing an ibatis-spring jar. Unfortunately there will be impact in old code because we cannot use the org.springframework package name.

**Comment by emacarron** [comment]
I have just copy & pasted code to here: https://github.com/mybatis/ibatis-spring

Opinions?

**Comment by hazendaz** [comment]
Cool.  Thanks.  I'll look at this soon.


Sent by Outlook for Android





On Sun, Nov 1, 2015 at 10:21 AM -0800, "Eduardo Macarron" <notifications@github.com> wrote:
I have just copy & pasted code to here: https://github.com/mybatis/ibatis-spring

Opinions?



---

**Comment by hazendaz** [comment]
I wonder if there is any reason to not keep package as is.  Just change the pom to mybatis style so we can release.  I'll try to test this sometime this week with a project we have still on ibatis and only stuck on spring 3 due to that.  At least something easy I can try out.


Sent by Outlook for Android





On Sun, Nov 1, 2015 at 7:58 PM -0800, <jeremylandis@hotmail.com> wrote:
Cool.  Thanks.  I'll look at this soon.


Sent by Outlook for Android





On Sun, Nov 1, 2015 at 10:21 AM -0800, "Eduardo Macarron" <notifications@github.com> wrote:
I have just copy & pasted code to here: https://github.com/mybatis/ibatis-spring

Opinions?



---

**Comment by hazendaz** [comment]
I suppose we could use a couple of maven plugins to simple pull from spring piece directly so we don't even have the code.  That would make it cleaner to use in case they patch something in 3.2.x regarding this although that is probably unlikely.  Thoughts?


Sent by Outlook for Android





On Sun, Nov 1, 2015 at 8:02 PM -0800, <jeremylandis@hotmail.com> wrote:
I wonder if there is any reason to not keep package as is.  Just change the pom to mybatis style so we can release.  I'll try to test this sometime this week with a project we have still on ibatis and only stuck on spring 3 due to that.  At least something easy I can try out.


Sent by Outlook for Android





On Sun, Nov 1, 2015 at 7:58 PM -0800, <jeremylandis@hotmail.com> wrote:
Cool.  Thanks.  I'll look at this soon.


Sent by Outlook for Android





On Sun, Nov 1, 2015 at 10:21 AM -0800, "Eduardo Macarron" <notifications@github.com> wrote:
I have just copy & pasted code to here: https://github.com/mybatis/ibatis-spring

Opinions?



---

**Comment by emacarron** [comment]
Hi @hazendaz 

I am not sure we will be able to release something in the org.springframework namespace to maven central. Probably it will be rejected. Not sure about this.

I like the idea of doing this just with maven. We can for example just repackage springs jar with jarjar or similar into the org.mybatis. The only problem I see is that we won't be able to fix something by ourselves but OTOH I doubt we will find a bug in that small code after 10 years of production :)

**Comment by hazendaz** [comment]
@emacarron This will still go to central under mybatis branding.  That is handled by the pom.  I've got it completed.  Before I did this, I did bump to spring 4.2.2 to see if there were any conditions that might cause issues.  Other than some deprecated classes, it works for now.  So I'll go ahead and push this out to central.  Being that it's 100% identical to spring under using the shade plugin I don't see any real need to take our time.  Plus those that benefit will be somewhat small.  What I'll do on Monday is give this a go at my day job to verify it works as expected.  I'll be testing against the last ibatis copy released before it becamse mybatis2.

@mokhtar-ahmed Give it a couple of hours to show up in maven central.  Then let me know if that works for you as well.  Once we have both verified, I'll close this issue.

project by the way which was mentioned earlier is here for that integration -> https://github.com/mybatis/ibatis-spring

**Comment by hazendaz** [comment]
I've ran this along with what we pulled from spring for ibatis 2 support along with spring 4.2.2.Final.  All worked well so closing this issue.

Use the following along with mybatis2 or even ibatis 2 versions to allow upgrade to spring 4.

<dependency>
    <groupId>org.mybatis</groupId>
    <artifactId>mybatis-2-spring</artifactId>
    <version>1.0.1</version>
</dependency>
