### ISSUE TITLE
SqlMapClasspathEntityResolver uses Locale dependent Operations

### ISSUE THREAD

**Issue by TheGoesen** [mybatis/ibatis-2#40]
The class in question uses `toUpperCase()` instead of `toUpperCase(Locale.ROOT)`
So the code fails given following setup:
The static map gets initialized using a english locale.
The user switches to the turkish locale and starts to resolve his documents.

I looked at the code and it seems like this is already fixed in mybatis 3.  
I would suggest to simply migrate this class to use `toUpperCase(Locale.ROOT)`, thats easy, should fix this and i cannot see it breaking anything.

**Comment by hazendaz** [comment]
Can you send a pull request with comment pointing to mybatis 3 code with same fix that way it's more clear and I'll take care of merging that once you submit it?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by TheGoesen** [comment]
Hello, 
I am not sure if I understand you correctly. The bug should be fixed in batis 3.
So do you want a patch against ibatis 2 that fixes it the same way I suggested,
or a patch that fixes it the same way it's done in mybatis 3?

**Comment by hazendaz** [comment]
Sorry,  what I was getting at is that you said ibatis2 line has this bug and it's fixed in mybatis3.  So for reference on your pull request a link to where it's fixed in mybatis3 is only to point it out better so it's easier to confirm the bug.  No need to do anything beyond the fix.  Ibatis2 line is End of life so only trivial bugs like this would warrant us releasing which I will do.

Hope that helps

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by hazendaz** [comment]
Closing issue as very old and this library set is unsupported at this point.  If a pull request for same comes along it will be merged and release made.  Issue alone will not get anything fixed unfortunately.
