### ISSUE TITLE
iBatis Cachemodel for custom type handler

### ISSUE THREAD

**Issue by Khalees2** [mybatis/ibatis-2#67]
I am trying to use cache model to cache the results returned from a procedure. But every time I hit the DB, It stores 'SERIALIZABLE NULL OBJECT' and the second time I hit the DB, it says cache miss and stores 'SERIALIZABLE NULL OBJECT'. I am using iBatis 2 and calling a procedure.

XML file looks like this:
![image](https://user-images.githubusercontent.com/45350631/80196091-c3c29a80-8614-11ea-8f6c-a77cae5de7db.png)

**Comment by harawata** [comment]
Hello @Khalees2 ,

Is it supposed to work?
I don't know anything about caching in iBATIS 2. but I know that the result of stored procedures cannot be cached in MyBatis 3.

**Comment by Khalees2** [comment]
Hello @harawata,

My issue still exists, I am still not able cache the results returned by procedure when custom typehandler is used. Caching works for stored procedure when custom type handler is not used.
Does anyone know? how we can handle caching when custom type handler is used?

**Comment by hazendaz** [comment]
with ibatis-2 being out of support generally, you would be best to start upgrading to mybatis 3 which you can do in chunks as the setup/imports do not overlap.  Otherwise, anything here if an issue, you would need to address / raise pull request which I'll be happy to merge / get released.  I think otherwise you may need to hit up the user groups.  Obviously legacy ibatis 2 is still pretty heavily used but probably mostly for wrong reasons (ie not knowing it is not a big bang upgrade).

**Comment by Khalees2** [comment]
Hi @hazendaz 

I found out the root cause of this issue and fixed it. It's a bug in the framework in which it is not adding results returned by **Procedures** to the cache model. 

Regards,
Salman

**Comment by hazendaz** [comment]
Sure @Khalees2 , I'd be happy to merge a PR and get it released for you.

**Comment by hazendaz** [comment]
@Khalees2 I'm likley to release a copy of this in coming weeks.  If you were still able to work on PR here that would be great.

**Comment by hazendaz** [comment]
closing ticket as @Khalees2 noted it was fixed but never submitted a pull request for fixing.  Since no fix produced, closing ticket.  If a fix comes will certainly merge it otherwise.
